# frozen_string_literal: true

# End-to-end tests: a real OpenVox server compiles the module for an ACME
# worker and a consumer node (profile e2e in spec/acceptance/compose.yml) -
# run them with `bundle exec rake acceptance:e2e`. The Hiera data holds only
# per-run credentials generated by AcceptanceEnv.
require 'yaml'
require_relative '../acceptance_helper'

# Configuration of the OpenVox server's production environment and agent runs.
module E2eEnv
  ENVIRONMENT = '/etc/puppetlabs/code/environments/production'
  WORKER = 'worker.acceptance.test'
  CERTIDS = { consul: 'e2e-consul', redis: 'e2e-redis' }.freeze

  module_function

  def compose(*args)
    ['docker', 'compose', '-f', AcceptanceEnv::COMPOSE, '--profile', 'e2e', *args]
  end

  def deploy_dir(backend)
    "/etc/e2e/#{backend}"
  end

  def hiera_data(certificates)
    consul = AcceptanceEnv.consul_tokens.fetch('web')
    redis = AcceptanceEnv.redis_users.fetch('web')
    {
      'acme_kvstore::prefix' => AcceptanceEnv::PREFIX,
      'acme_kvstore::backend' => 'consul',
      'acme_kvstore::consul' => { 'url' => 'http://consul:8500' },
      'acme_kvstore::redis' => { 'host' => 'redis', 'port' => 6379 },
      'acme_kvstore::areas' => {
        'web' => {
          'secret' => AcceptanceEnv.area_secret,
          'consul_token' => consul.fetch('write'),
          'consul_read_token' => consul.fetch('read'),
          'redis_username' => redis.dig('write', 'username'),
          'redis_password' => redis.dig('write', 'password'),
          'redis_read_username' => redis.dig('read', 'username'),
          'redis_read_password' => redis.dig('read', 'password'),
        },
      },
      'acme_kvstore::ca_profiles' => { 'pebble' => { 'directory_url' => 'https://pebble:14000/dir' } },
      'acme_kvstore::ca_whitelist' => ['pebble'],
      'acme_kvstore::default_ca_profile' => 'pebble',
      'acme_kvstore::default_worker' => WORKER,
      'acme_kvstore::default_area' => 'web',
      # Pebble's default profile issues 6-day certificates.
      'acme_kvstore::renew_before_days' => 1,
      'acme_kvstore::worker::manage_user' => true,
      'acme_kvstore::worker::manage_gems' => true, # the worker writes to Redis too
      'acme_kvstore::worker::install_method' => ENV.fetch('E2E_INSTALL_METHOD', 'git'),
      'acme_kvstore::worker::user' => 'acme',
      'acme_kvstore::worker::group' => 'acme',
      'acme_kvstore::certificates' => certificates,
    }
  end

  def default_certificates
    CERTIDS.to_h do |backend, certid|
      [certid, { 'domain' => "#{certid}.example.test", 'backend' => backend.to_s, 'key_type' => 'ec', 'key_size' => 256 }]
    end
  end

  def site_pp
    deploys = CERTIDS.map do |backend, certid|
      dir = deploy_dir(backend)
      <<~PUPPET
        file { '#{dir}': ensure => directory }
        acme_kvstore::deploy { '#{certid}':
          backend        => '#{backend}',
          cert_path      => '#{dir}/cert.pem',
          key_path       => '#{dir}/key.pem',
          chain_path     => '#{dir}/chain.pem',
          fullchain_path => '#{dir}/fullchain.pem',
          combined_path  => '#{dir}/combined.pem',
          dh_path        => '#{dir}/dh.pem',
          require        => File['#{dir}'],
        }
      PUPPET
    end
    <<~PUPPET
      node '#{WORKER}' {
        include acme_kvstore
      }

      # A consumer needs neither the acme_kvstore class nor worker credentials.
      node 'consumer.acceptance.test' {
        file { '/etc/e2e': ensure => directory }
      #{deploys.join.gsub(%r{^(?=.)}, '  ')}}
    PUPPET
  end

  def hiera_yaml
    { 'version' => 5, 'hierarchy' => [{ 'name' => 'common', 'path' => 'common.yaml' }] }.to_yaml
  end

  # Writes the environment (manifests, Hiera) into the server. `compose cp`
  # keeps the host's owner; root-owned 0640 files are readable by the
  # server's user through its group root.
  def configure(certificates = default_certificates)
    dir = File.join(AcceptanceEnv.workdir, 'environment')
    FileUtils.mkdir_p([File.join(dir, 'manifests'), File.join(dir, 'data')])
    { 'manifests/site.pp' => site_pp, 'hiera.yaml' => hiera_yaml, 'data/common.yaml' => hiera_data(certificates).to_yaml }.each do |path, content|
      File.open(File.join(dir, path), 'w', 0o640) { |file| file.write(content) }
    end
    AcceptanceEnv.run!(*compose('cp', "#{dir}/.", "openvoxserver:#{ENVIRONMENT}/"))
    AcceptanceEnv.run!(*compose('exec', '-T', '-u', 'root', 'openvoxserver', 'chown', '-R', 'root:root',
                                *%w[manifests data hiera.yaml].map { |path| "#{ENVIRONMENT}/#{path}" }))
  end

  # Runs the agent; returns its exit code (--detailed-exitcodes) and output.
  def agent(node)
    output, status = Open3.capture2e(*compose('exec', '-T', node, 'puppet', 'agent', '--test', '--server', 'openvoxserver', '--color', 'false'))
    [status.exitstatus, output]
  end

  def node_exec(node, *command)
    AcceptanceEnv.run!(*compose('exec', '-T', node, *command))
  end
end
