# frozen_string_literal: true

require 'voxpupuli/test/spec_helper'

# Module-specific customisation lives in spec_helper_local.rb, never here:
# this file mirrors the upstream Voxpupuli-managed template and may be
# regenerated by tooling in future. See spec/spec_helper_local.rb for this
# module's own load-path addition.
require 'spec_helper_local' if File.file?(File.join(File.dirname(__FILE__), 'spec_helper_local.rb'))
